### ISSUE TITLE
Add Documentation how to manage antora specs

### ISSUE THREAD

**Issue by zrgt** [rwth-iat/aas-specs-antora#11]
## Background
We need a short documentation for other users how to manage antora specs.

## Task
Add the following points to the `README.MD` (links to articles would also be ok):
- [ ]  How to add New doc repos in `aas-specs-antora` Repo
- [ ]  How doc repo must be structured for Antora 
- [ ]  How to manually trigger building of web docs in Github

**Comment by zrgt** [comment]
Here is a draft:
--------------------------

# Managing Antora Specs Documentation

This guide provides a brief overview of how to manage documentation repositories (Doku-Repos) for Antora specs, including adding new repositories, structuring them appropriately, and manually triggering web documentation updates on GitHub.

## Adding New Documentation Repositories for Antora

To add new documentation repositories for use with Antora, follow these steps:

1. **Create a New Repository**: On GitHub, create a new repository to hold your AsciiDoc content. This repository will be integrated with Antora to generate your documentation site.
   
2. **Configure Antora**: In the `antora-playbook.yml` file of your documentation site generator, add the new repository under the `content.sources` section. Specify the `url` of your new repository and the `branches` to track.

   ```yaml
   content:
     sources:
       - url: https://github.com/<your-organization>/<new-repo-name>
         branches: [main]
   ```

3. **Commit and Push**: Save your changes to the `antora-playbook.yml` file, commit, and push them to your repository.

For detailed instructions, refer to [Antora's official documentation on configuring content sources](https://docs.antora.org/antora/latest/configure-content-sources/).

## Structuring Documentation Repositories for Antora

An Antora documentation repository must be structured to include at least the following:

- **Modules Directory**: Contains the documentation components, divided into multiple modules for organization.
- **Pages Directory**: Within each module, a `pages` directory holds the AsciiDoc files (.adoc) containing your documentation content.
- **Nav.adoc File**: A navigation file within each module directory to define the structure of your documentation in the generated site.

Example structure:

```
docs/
  modules/
    module-name/
      pages/
        index.adoc
      nav.adoc
```

For a comprehensive guide on structuring your documentation for Antora, see [Antora's official documentation on directory structure](https://docs.antora.org/antora/latest/standard-directories/).

## Manually Triggering Web Documentation on GitHub

To manually trigger the generation and deployment of your web documentation on GitHub:

1. **Navigate to Your Repository**: Go to the GitHub repository where your documentation source or Antora playbook is hosted.
   
2. **Access Actions Tab**: Click on the "Actions" tab.
   
3. **Run Workflow**: Find the workflow responsible for generating and deploying your documentation (it may be named something like "Deploy Docs" or "Antora Publish"). Click on "Run workflow", select the branch you want to deploy from, and then click "Run workflow" again.

For more detailed steps or to set up a workflow if you haven't already, consult [GitHub's documentation on manually triggering a workflow](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow).

**Comment by monsieuremre** [comment]
Addressed with https://github.com/rwth-iat/aas-specs-antora/commit/357b84b8b220589d32aa510da36b7197c32bb2b6.

**Comment by monsieuremre** [comment]
When it comes to the document and folder structure etc., I think it would be easier to just continue using our orphan github branch, at least alongside with the upstream sources.

For example, there is a [pull request](https://github.com/admin-shell-io/aas-specs-aasx/pull/6) to fix a problem in Part 5, where the cover page basically blocks navigation and breaks the website. So it takes some time until we push our fixes and changes upstream one by one.

Instead of that, I think we can fix everything in our orphan branch, and upstream can just copy from us the final result as a whole. They are e.g. interested in splitting the index files into several main segments. If they can just specify what to be split, we can easily implement everything as a whole in a more compact and integrated and a much quicker way in our orphan repository, and upstream can just have it from there, again as a complete whole.

Would this not be more desirable?

This may or may not be the right place to mention and disuss this topic. I chose here because we are doing the folder structure etc. documentation in this issue practically. So I think, if the aim is to help upstream with the folder structure, this might be a faster way than just providing them documentation, which we absolutely also do.

**Comment by monsieuremre** [comment]
Since the download button is added, the superfluous links and text components are deleted from the readme file. Is there anything to imporve it further or should be close this issue?

**Comment by zrgt** [comment]
The issue can be closed
